name: Render Keep Alive Cron

on:
  schedule:
    # Runs every 4 minutes
    - cron: '*/4 * * * *'
  workflow_dispatch:

jobs:
  ping-render:
    runs-on: ubuntu-latest
    steps:
      - name: Send Ping Request to Render API
        run: |
          curl -s -f "https://vehicle-master-api.onrender.com/api/v1/vehicle/GJ01MZ8989" > /dev/null
          echo "Ping successful! Render app kept alive at $(date)"
